export const ERROR_CODES = {
  AUTH: {
    DUPLICATE_EMAIL: "DUPLICATE_EMAIL",
    DUPLICATE_NICKNAME: "DUPLICATE_NICKNAME",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    LOGIN_REQUIRED: "LOGIN_REQUIRED",
    EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
    PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
    ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
    TOO_MANY_ATTEMPTS: "TOO_MANY_ATTEMPTS",
  },
  DATA: {
    NO_DATA: "NO_DATA",
    INVALID_RESPONSE: "INVALID_RESPONSE",
  },
  USER: {
    NOT_FOUND: "USER_NOT_FOUND",
    UNAUTHORIZED: "UNAUTHORIZED",
  },
  COMMON: {
    NETWORK_ERROR: "NETWORK_ERROR",
    INTERNAL_ERROR: "INTERNAL_ERROR",
  },
} as const;
