import type { Metadata } from "next";
import Providers from "@/shared/lib/providers/Providers";
import { Header } from "@/widgets/header/ui/header";
import { authOptions } from "@/features/auth/lib/next-auth";
import { getServerSession } from "next-auth";

import "./globals.css";

export const metadata: Metadata = {
  title: "스터디 화이팅!!",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <Providers session={session}>
          <div className="min-h-screen bg-gray-50">
            <Header />
            <main className="container mx-auto py-6 px-4">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
