import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/shared/lib/providers/Providers";
import { Header } from "@/widgets/header/ui/header";

export const metadata: Metadata = {
  title: "스터디 화이팅!!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="min-h-screen bg-gray-50">
            <Header />
            <main className="container mx-auto py-6 px-4">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
